# site settings
title: Maison Vet
subtitle: CLÍNICA VETERINÁRIA
email: clinica.maisonvet@gmail.com
description: Clinica veterinária em valinhos.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: R. ASSUERO PÊRA, 5 - JD. BOA ESPERANÇA
city: VALINHOS
state: SP
zip_code: 13270-383
phone: (19) 3849-6944

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/clinicamaisonvet/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/clinicamaisonvet/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
